dist: xenial
language: rust
matrix:
  include:
    - os: linux
      rust: nightly
      env: GTK=3.14 FEATURES=
    - os: linux
      rust: nightly
      env: GTK=3.24 FEATURES=v3_16
    - os: linux
      rust: beta
      env: GTK=3.14 FEATURES=
    - os: linux
      rust: beta
      env: GTK=3.24 FEATURES=v3_16
    - os: linux
      rust: stable
      env: GTK=3.14 FEATURES=
    - os: linux
      rust: stable
      env: GTK=3.24 FEATURES=v3_16
    - os: linux
      rust: 1.39.0
      env: GTK=3.14 FEATURES=
    - os: linux
      rust: 1.39.0
      env: GTK=3.24 FEATURES=v3_16
    - os: osx
      rust: nightly
      env: GTK=3.14 FEATURES=
    # - os: osx
    #   rust: nightly
    #   env: GTK=3.24 FEATURES=v3_16
    - os: osx
      rust: beta
      env: GTK=3.14 FEATURES=
    # - os: osx
    #   rust: beta
    #   env: GTK=3.24 FEATURES=v3_16
    - os: osx
      rust: stable
      env: GTK=3.14 FEATURES=
    # - os: osx
    #   rust: stable
    #   env: GTK=3.24 FEATURES=v3_16
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libmount-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python@2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtk+3 cairo atk; fi
script:
  - rustc --version
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ] && [ "$GTK" == "3.14" ]; then
    rustup component add rustfmt;
    make regen_check;
    fi
  - ./check_init_asserts
  - cargo doc --features "dox,embed-lgpl-docs"
  - cargo test --features "$FEATURES,embed-lgpl-docs"
  # catch any sneaked in lgpl docs
  - cargo build --features "$FEATURES,purge-lgpl-docs" --jobs 1
  - git diff -R --exit-code
  - rustc --version
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples
  - cd _examples
  - ./build_travis.sh
