// This file was generated by gir (c3b4020) from gir-files (71d73f0)
// DO NOT EDIT

use ffi;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct RGBA(Boxed<ffi::GdkRGBA>);

    match fn {
        copy => |ptr| ffi::gdk_rgba_copy(mut_override(ptr)),
        free => |ptr| ffi::gdk_rgba_free(ptr),
    }
}

impl RGBA {
    pub fn parse(&mut self, spec: &str) -> bool {
        unsafe {
            from_glib(ffi::gdk_rgba_parse(self.to_glib_none_mut().0, spec.to_glib_none().0))
        }
    }

    fn to_string(&self) -> String {
        unsafe {
            from_glib_full(ffi::gdk_rgba_to_string(self.to_glib_none().0))
        }
    }
}

impl fmt::Display for RGBA {
    #[inline]
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.to_string())
    }
}
